# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: placeB - Lagerraum von placeB - Dein online Self-Storage in der Schweiz
email: info@placeb.ch
description: > # this means to ignore newlines until "baseurl:"
  Die Lagerlösung in deiner Nähe - Selfstorage online,
  rund um die Uhr und in individuellen trockenen und geheizten Boxen - das ist placeB.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.placeb.ch" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems:
- jekyll-assets

sass:
    style: compressed

exclude: ["deploy"]

assets:
  features:
    automatic_img_size: false
  compress:
    css:  sass
    js:   uglifier

sources:
  - "_assets/folder"


sitemap:
    exclude:
        - "/pricing.html"