FOS\UserBundle\Model\User:
    properties:
        username:
            exclude: true
        usernameCanonical:
            exclude: true
        emailCanonical:
            exclude: true
        enabled:
            exclude: true
        salt:
            exclude: true
        password:
            exclude: true
        plainPassword:
            exclude: true
        lastLogin:
            exclude: true
        confirmationToken:
            exclude: true
        passwordRequestedAt:
            exclude: true
        groups:
            exclude: true
        locked:
            exclude: true
        expired:
            exclude: true
        expiresAt:
            exclude: true
        roles:
            exclude: true
        credentialsExpired:
            exclude: true
        credentialsExpireAt:
            exclude: true