imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
        mail:
            type:         fingers_crossed
            # 500 errors are logged at the critical level
            action_level: error
            # to also log 400 level errors (but not 404's):
            # action_level: error
            excluded_404s:
                - ^/
            handler:      grouped
        grouped:
            type:    group
            members: [buffered_slack, buffered_swift, buffered_sms]
        buffered_swift:
            type:    buffer
            handler: swift
        buffered_slack:
            type:    buffer
            handler: slack
        buffered_sms:
            type:    buffer
            handler: sms
        swift:
            type:       swift_mailer
            from_email: %admin_email%
            to_email:   %error_event_emails%
            subject:    An Error Occurred!
            level:      debug
        slack:
            type:   service
            id:     error.handler.slack
            level:      debug
        sms:
            type:   service
            id:     error.handler.sms
            level:  critical

