app:
    resource: "@AppBundle/Controller/"
    type:     annotation


fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

# FOSUserBundle's routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

# If remove this we have sonata admin issue
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

# Admin's routing
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /