AppBundle\Entity\Box:
    properties:
        boxStatus:
            exclude: true
        boxDoor:
            exclude: true
        created:
            exclude: true
        updated:
            exclude: true